services:
  nginx:
    container_name: sdl_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
      - "8080:80"
    links:
      - php-fpm
  
  php-fpm:
    container_name: sdl_php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    links:
      - mysql
  
  php-cli:
    container_name: sdl_php-cli
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql
    tty: true
  
  mysql:
    container_name: sql_mysql
    image: mysql:8.0
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    ports:
      - "33061:3306"
