services:
  nginx:
    container_name: sdl_nginx
    build:
      context: ./docker/config/nginx
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    ports:
      - "8090:80"
    depends_on:
      - php-fpm
    networks:
      - sample-network

  php-fpm:
    container_name: sdl_php-fpm
    build:
      context: ./docker/config/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www
    environment:
      - "DB_PORT=3306"
    networks:
      - sample-network

  php-cli:
    container_name: sdl_php-cli
    build:
      context: ./docker/config/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www
    environment:
      - "DB_PORT=3306"
      - "COMPOSER_MEMORY_LIMIT=-1"
    tty: true
    networks:
      - sample-network

  mysql:
    container_name: sdl_mysql8
    image: mysql:8.0
    volumes:
      - ./docker/databases/mysql8:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    ports:
      - "13306:3306"
    networks:
      - sample-network

#  node:
#    container_name: sql_nodejs
#    image: node:18-alpine
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./:/var/www
#    working_dir: /var/www
#    tty: true

networks:
  sample-network:
    driver: bridge