services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    volumes:
      - ../files:/var/www
    ports:
      - "8090:80"
    tty: true
    networks:
      - network

  php-fpm-prod:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm-prod
    build:
      context: ./configs/php-fpm-prod
      dockerfile: Dockerfile
    volumes:
      - ../files:/var/www
    networks:
      network:
        aliases:
          - php-fpm

  php-fpm-dev:
    extends:
      service: php-fpm-prod
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm-dev
    build:
      context: ./configs/php-fpm-dev
      dockerfile: Dockerfile
      args:
        - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
    volumes:
      - ../files:/var/www
    environment:
      - "COMPOSER_MEMORY_LIMIT=-1"
    tty: true
    networks:
      network:
        aliases:
          - php-fpm

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./configs/mysql
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./databases/mysql:/var/lib/mysql:rw
      - ./configs/mysql/:/docker-entrypoint-initdb.d/:rw
    ports:
      - "13306:3306"
    tty: true
    networks:
      - network

  node:
    container_name: ${COMPOSE_PROJECT_NAME}_nodejs
    build:
      context: ./configs/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../files:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - network

networks:
  network:
    driver: bridge