services:
  nginx:
    container_name: sdl_nginx
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    volumes:
      - ../files:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    ports:
      - "8090:80"
    depends_on:
      - php-fpm
    networks:
      - sample-network

  php-fpm:
    container_name: sdl_php-fpm
    build:
      context: ./configs/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../files:/var/www
    environment:
      - "DB_PORT=3306"
    networks:
      - sample-network

  php-cli:
    container_name: sdl_php-cli
    build:
      context: ./configs/php-cli
      dockerfile: Dockerfile
      args:
        - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
    volumes:
      - ../files:/var/www
    environment:
      - "DB_PORT=3306"
      - "COMPOSER_MEMORY_LIMIT=-1"
    tty: true
    networks:
      - sample-network
    depends_on:
      - php-fpm

  mysql:
    container_name: sdl_mysql
    build:
      context: ./configs/mysql
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./databases/mysql:/var/lib/mysql:rw
      - ./configs/mysql/:/docker-entrypoint-initdb.d/:rw
    ports:
      - "13306:3306"
    networks:
      - sample-network

  node:
    container_name: sql_nodejs
    build:
      context: ./configs/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../files:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - sample-network

networks:
  sample-network:
    driver: bridge
    