services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    volumes:
      - ./../../files:/var/www
    ports:
      - "8090:80"
    tty: true
    networks:
      - network
    depends_on:
      - php-fpm

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: ./configs/php-fpm
      dockerfile: Dockerfile
      target: ${COMPOSE_PROJECT_TYPE} # prod\dev
    volumes:
      - ./../../files:/var/www
    tty: true
    networks:
      - network
    depends_on:
      - mysql

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./configs/mysql
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./../../data/mysql:/var/lib/mysql:rw
      - ./configs/mysql/:/docker-entrypoint-initdb.d/:rw
    ports:
      - "13306:3306"
    tty: true
    networks:
      - network

  node:
    container_name: ${COMPOSE_PROJECT_NAME}_nodejs
    build:
      context: ./configs/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./../../files:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - network

networks:
  network:
    driver: bridge