services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./configs/nginx
      dockerfile: Dockerfile
    volumes:
      - ./../files:/var/www:rw
    ports:
      - "8090:80"
    tty: true
    networks:
      - network
    depends_on:
      - php-fpm
    profiles:
      - backend
      - frontend

  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: ./configs/php-fpm
      dockerfile: Dockerfile
      target: ${COMPOSE_PROJECT_TYPE} # prod\dev
    volumes:
      - ./../files:/var/www
    tty: true
    networks:
      - network
    depends_on:
      - mysql
    profiles:
      - backend
      - frontend

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./configs/mysql
      dockerfile: Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./configs/mysql/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "13306:3306"
    tty: true
    env_file:
      - .env
    networks:
      - network
    profiles:
      - backend
      - frontend

  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}_mongodb
    build:
      context: ./configs/mongodb
      dockerfile: Dockerfile
    volumes:
      - ./data/mongodb:/data/db:rw
      - ./configs/mongodb/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    ports:
      - "37017:27017"
    tty: true
    networks:
      - network
    env_file:
      - .env

  memcached:
    container_name: ${COMPOSE_PROJECT_NAME}_memcached
    build:
      context: ./configs/memcached
      dockerfile: Dockerfile
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    tty: true
    networks:
      - network
  
#  redis: #todo add
#  manticoresearch: #todo add (fork of sphinx)  
  
  nodejs:
    container_name: ${COMPOSE_PROJECT_NAME}_nodejs
    build:
      context: ./configs/nodejs
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./../files:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - network
    profiles:
      - frontend

networks:
  network:
    driver: bridge