services:
  nginx:
    extends:
      file: docker-compose.prod.yml
      service: nginx
    depends_on:
      - php-fpm-dev

  php-fpm-dev:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm-dev
    build:
      context: ./configs/php-fpm-dev
      dockerfile: Dockerfile
      args:
        - COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
    volumes:
      - ../files:/var/www
    environment:
      - "COMPOSER_MEMORY_LIMIT=-1"
    tty: true
    networks:
      network:
        aliases:
          - php-fpm

  mysql:
    extends:
      file: docker-compose.prod.yml
      service: mysql

  node:
    extends:
      file: docker-compose.prod.yml
      service: node
    depends_on:
      - php-fpm-dev
      
networks:
  network:
    driver: bridge