FROM node:23.6.0

#RUN npm install
#RUN #apt-get update && apt-get install -y libmcrypt-dev mariadb-client \
##    && docker-php-ext-install pdo_mysql pcntl


#RUN docker-php-ext-configure exif
#RUN docker-php-ext-install exif
#RUN docker-php-ext-enable exif


#RUN #apt-get install -y wget unzip curl git vim
#RUN curl -sS https://getcomposer.org/installer |php
#RUN mv composer.phar /usr/local/bin/composer
#
#RUN apt-get install -y cron

# node image already has 1000:1000 = node:node
USER node:node

#WORKDIR /var/www

#CMD ["npm", "run", "dev"]
#CMD ["npm", "start"]